package com.example.app.entity;

public enum NotificationType {
  MEMBERSHIP_EXPIRY,
  MEMBERSHIP_RENEWAL,
  PAYMENT_SUCCESS,
  PAYMENT_FAILURE,
  APPOINTMENT_CONFIRMATION,
  APPOINTMENT_CANCELLATION,
  CLASS_REGISTRATION,
  CLASS_CANCELLATION,
  ATTENDANCE_REMINDER
}
